spring:
######################################### 运行环境 #########################################
  profiles:
    active: dev
######################################### database #########################################
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
########################################## aop #########################################
  aop:
    proxy-target-class: true
######################################### jsp #########################################
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp



# 项目contextPath，一般在正式发布版本中，我们不配置
#server.context-path=/myspringboot
# 错误页，指定发生错误时，跳转的URL。请查看BasicErrorController源码便知
#server.error.path=/error
# 服务端口
#server.port=9090
# session最大超时时间(分钟)，默认为30
#server.session-timeout=60
# 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置
# server.address=192.168.16.11


######################################### mybatis #########################################
mybatis:
  mapperLocations: classpath*:mapper/*.xml



######################################### log #########################################
logging:
  level:
    root: INFO